### ISSUE TITLE
UserInput demo is not running on Linux

### ISSUE THREAD

**Issue by xcom169** [STREGAsGate/GateEngine#49]
Hello All,
Do you know why the UserInput program is not compiling on Linux?

Default initializer for 'TextComponent' cannot be both nonisolated and main actor-isolated

Static property 'componentID' is not concurrency-safe because non-'Sendable' type 'ComponentID' may have shared mutable state
![image](https://github.com/user-attachments/assets/4a468a32-984c-45b2-b3cd-1775a2e99b38)

**Comment by STREGA** [comment]
Hey! Those are Swift 6 errors. Swift 6 has very strict requirements and GateEngine is not compatible yet.

You can try adding the `swiftLanguageVersions: [.v5]` to the Package.swift which should work. 
But if not, you'll need to build with the 5.10 toolchain.

**Comment by felipetesc** [comment]
Followed your instructions by adding `.swiftLanguageMode(.v5),` to swiftSettings and I can  confirm it works on Windows.

**Comment by xcom169** [comment]
Yes, after my targets [ ] I had to include ,swiftLanguageVersions: [.v5]    .
  Thanks!
